class ExampleFSM(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2019-08-01 22:28:40 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 20
        self.input_vars = ['red', 'notclear']

    def move(self, red, notclear):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['intersection', 'goal', 'signal', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (notclear == False) and (red == False):
                self.state = 4

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == False) and (red == True):
                self.state = 5

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == False):
                self.state = 6

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == True):
                self.state = 7

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red, notclear)
        elif self.state == 1:
            if (notclear == False) and (red == False):
                self.state = 4

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == False) and (red == True):
                self.state = 5

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == False):
                self.state = 6

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == True):
                self.state = 7

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red, notclear)
        elif self.state == 2:
            if (notclear == False) and (red == False):
                self.state = 4

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == False) and (red == True):
                self.state = 5

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == False):
                self.state = 6

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == True):
                self.state = 7

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red, notclear)
        elif self.state == 3:
            if (notclear == False) and (red == False):
                self.state = 4

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == False) and (red == True):
                self.state = 5

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == False):
                self.state = 6

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == True):
                self.state = 7

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red, notclear)
        elif self.state == 4:
            if (notclear == False) and (red == False):
                self.state = 8

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == False) and (red == True):
                self.state = 9

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == True) and (red == False):
                self.state = 10

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == True) and (red == True):
                self.state = 11

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            else:
                self._error(red, notclear)
        elif self.state == 5:
            if (notclear == False) and (red == False):
                self.state = 4

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == False) and (red == True):
                self.state = 5

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == False):
                self.state = 6

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == True):
                self.state = 7

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red, notclear)
        elif self.state == 6:
            if (notclear == False) and (red == False):
                self.state = 4

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == False) and (red == True):
                self.state = 5

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == False):
                self.state = 6

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == True):
                self.state = 7

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red, notclear)
        elif self.state == 7:
            if (notclear == False) and (red == False):
                self.state = 4

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == False) and (red == True):
                self.state = 5

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == False):
                self.state = 6

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (notclear == True) and (red == True):
                self.state = 7

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red, notclear)
        elif self.state == 8:
            if (notclear == False) and (red == False):
                self.state = 12

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            elif (notclear == False) and (red == True):
                self.state = 13

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            elif (notclear == True) and (red == False):
                self.state = 14

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            elif (notclear == True) and (red == True):
                self.state = 15

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            else:
                self._error(red, notclear)
        elif self.state == 9:
            if (notclear == False) and (red == False):
                self.state = 12

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            elif (notclear == False) and (red == True):
                self.state = 13

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            elif (notclear == True) and (red == False):
                self.state = 14

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            elif (notclear == True) and (red == True):
                self.state = 15

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X6'
            else:
                self._error(red, notclear)
        elif self.state == 10:
            if (notclear == False) and (red == False):
                self.state = 8

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == False) and (red == True):
                self.state = 9

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == True) and (red == False):
                self.state = 10

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == True) and (red == True):
                self.state = 11

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            else:
                self._error(red, notclear)
        elif self.state == 11:
            if (notclear == False) and (red == False):
                self.state = 8

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == False) and (red == True):
                self.state = 9

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == True) and (red == False):
                self.state = 10

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            elif (notclear == True) and (red == True):
                self.state = 11

                output["goal"] = False
                output["intersection"] = True
                output["signal"] = False
                output["loc"] = 'X3'
            else:
                self._error(red, notclear)
        elif self.state == 12:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 13:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 14:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 15:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 16:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 17:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 18:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 19:
            if (notclear == False) and (red == False):
                self.state = 16

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == False) and (red == True):
                self.state = 17

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == False):
                self.state = 18

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            elif (notclear == True) and (red == True):
                self.state = 19

                output["goal"] = True
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X7'
            else:
                self._error(red, notclear)
        elif self.state == 20:
            if (notclear == False) and (red == False):
                self.state = 0

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            elif (notclear == True) and (red == False):
                self.state = 1

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            elif (notclear == False) and (red == True):
                self.state = 2

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            elif (notclear == True) and (red == True):
                self.state = 3

                output["goal"] = False
                output["intersection"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            else:
                self._error(red, notclear)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, red, notclear):
        raise ValueError("Unrecognized input: " + (
            "red = {red}; "
            "notclear = {notclear}; ").format(
                red=red,
                notclear=notclear))
