class ExampleFSM(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2019-07-31 20:50:41 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 10
        self.input_vars = ['red']

    def move(self, red):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['signal', 'goal', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (red == False):
                self.state = 2

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            elif (red == True):
                self.state = 3

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            else:
                self._error(red)
        elif self.state == 1:
            if (red == False):
                self.state = 2

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            elif (red == True):
                self.state = 3

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X1'
            else:
                self._error(red)
        elif self.state == 2:
            if (red == False):
                self.state = 4

                output["goal"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (red == True):
                self.state = 5

                output["goal"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red)
        elif self.state == 3:
            if (red == False):
                self.state = 4

                output["goal"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (red == True):
                self.state = 5

                output["goal"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red)
        elif self.state == 4:
            if (red == False):
                self.state = 6

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X3'
            elif (red == True):
                self.state = 7

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X3'
            else:
                self._error(red)
        elif self.state == 5:
            if (red == False):
                self.state = 4

                output["goal"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            elif (red == True):
                self.state = 5

                output["goal"] = False
                output["signal"] = True
                output["loc"] = 'X2'
            else:
                self._error(red)
        elif self.state == 6:
            if (red == False):
                self.state = 8

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            elif (red == True):
                self.state = 9

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            else:
                self._error(red)
        elif self.state == 7:
            if (red == False):
                self.state = 8

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            elif (red == True):
                self.state = 9

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            else:
                self._error(red)
        elif self.state == 8:
            if (red == False):
                self.state = 8

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            elif (red == True):
                self.state = 9

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            else:
                self._error(red)
        elif self.state == 9:
            if (red == False):
                self.state = 8

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            elif (red == True):
                self.state = 9

                output["goal"] = True
                output["signal"] = False
                output["loc"] = 'X4'
            else:
                self._error(red)
        elif self.state == 10:
            if (red == False):
                self.state = 0

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X0'
            elif (red == True):
                self.state = 1

                output["goal"] = False
                output["signal"] = False
                output["loc"] = 'X0'
            else:
                self._error(red)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, red):
        raise ValueError("Unrecognized input: " + (
            "red = {red}; ").format(
                red=red))
