class ExampleFSM(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2019-08-06 00:37:58 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 20
        self.input_vars = ['road_clear', 'red']

    def move(self, road_clear, red):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['enter', 'stop2', 'turnleft', 'stop1', 'approach', 'signal', 'stop3', 'leave', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (red == False) and (road_clear == False):
                self.state = 0

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == True) and (road_clear == False):
                self.state = 1

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == False) and (road_clear == True):
                self.state = 2

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == True) and (road_clear == True):
                self.state = 3

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            else:
                self._error(road_clear, red)
        elif self.state == 1:
            if (red == False) and (road_clear == False):
                self.state = 0

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == True) and (road_clear == False):
                self.state = 1

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == False) and (road_clear == True):
                self.state = 2

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == True) and (road_clear == True):
                self.state = 3

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            else:
                self._error(road_clear, red)
        elif self.state == 2:
            if (red == False) and (road_clear == False):
                self.state = 4

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            elif (red == True) and (road_clear == False):
                self.state = 5

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            elif (red == False) and (road_clear == True):
                self.state = 6

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            elif (red == True) and (road_clear == True):
                self.state = 7

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            else:
                self._error(road_clear, red)
        elif self.state == 3:
            if (red == False) and (road_clear == False):
                self.state = 4

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            elif (red == True) and (road_clear == False):
                self.state = 5

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            elif (red == False) and (road_clear == True):
                self.state = 6

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            elif (red == True) and (road_clear == True):
                self.state = 7

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = True
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X2'
            else:
                self._error(road_clear, red)
        elif self.state == 4:
            if (red == False) and (road_clear == False):
                self.state = 8

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == False):
                self.state = 9

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == False) and (road_clear == True):
                self.state = 10

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == True):
                self.state = 11

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            else:
                self._error(road_clear, red)
        elif self.state == 5:
            if (red == False) and (road_clear == False):
                self.state = 8

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == False):
                self.state = 9

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == False) and (road_clear == True):
                self.state = 10

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == True):
                self.state = 11

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            else:
                self._error(road_clear, red)
        elif self.state == 6:
            if (red == False) and (road_clear == False):
                self.state = 8

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == False):
                self.state = 9

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == False) and (road_clear == True):
                self.state = 10

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == True):
                self.state = 11

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            else:
                self._error(road_clear, red)
        elif self.state == 7:
            if (red == False) and (road_clear == False):
                self.state = 8

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == False):
                self.state = 9

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == False) and (road_clear == True):
                self.state = 10

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            elif (red == True) and (road_clear == True):
                self.state = 11

                output["approach"] = False
                output["enter"] = True
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X3'
            else:
                self._error(road_clear, red)
        elif self.state == 8:
            if (red == False) and (road_clear == False):
                self.state = 12

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == False):
                self.state = 13

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == False) and (road_clear == True):
                self.state = 14

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == True):
                self.state = 15

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            else:
                self._error(road_clear, red)
        elif self.state == 9:
            if (red == False) and (road_clear == False):
                self.state = 12

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == False):
                self.state = 13

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == False) and (road_clear == True):
                self.state = 14

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == True):
                self.state = 15

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            else:
                self._error(road_clear, red)
        elif self.state == 10:
            if (red == False) and (road_clear == False):
                self.state = 12

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == False):
                self.state = 13

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == False) and (road_clear == True):
                self.state = 14

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == True):
                self.state = 15

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            else:
                self._error(road_clear, red)
        elif self.state == 11:
            if (red == False) and (road_clear == False):
                self.state = 12

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == False):
                self.state = 13

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == False) and (road_clear == True):
                self.state = 14

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            elif (red == True) and (road_clear == True):
                self.state = 15

                output["approach"] = False
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = True
                output["loc"] = 'X4'
            else:
                self._error(road_clear, red)
        elif self.state == 12:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 13:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 14:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 15:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 16:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 17:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 18:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 19:
            if (red == False) and (road_clear == False):
                self.state = 16

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == False):
                self.state = 17

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == False) and (road_clear == True):
                self.state = 18

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            elif (red == True) and (road_clear == True):
                self.state = 19

                output["approach"] = False
                output["enter"] = False
                output["leave"] = True
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X5'
            else:
                self._error(road_clear, red)
        elif self.state == 20:
            if (red == False) and (road_clear == False):
                self.state = 0

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == True) and (road_clear == False):
                self.state = 1

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == False) and (road_clear == True):
                self.state = 2

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            elif (red == True) and (road_clear == True):
                self.state = 3

                output["approach"] = True
                output["enter"] = False
                output["leave"] = False
                output["signal"] = False
                output["stop1"] = False
                output["stop2"] = False
                output["stop3"] = False
                output["turnleft"] = False
                output["loc"] = 'X1'
            else:
                self._error(road_clear, red)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, road_clear, red):
        raise ValueError("Unrecognized input: " + (
            "road_clear = {road_clear}; "
            "red = {red}; ").format(
                road_clear=road_clear,
                red=red))
